config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :addresses do
    get 'show_all', on: :collection
  end

  namespace :youtube do
    get 'most_popular', to: 'most_popular'
    get 'video_comments', to: 'video_comments'
  end

  namespace :flickr do
    get 'search', to: 'search'
    get 'show_photo', to: 'show_photo'
  end

  resources :movies

  wash_out 'api/soap/movies'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_address, only: [:edit, :update, :destroy]

  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    @address = Address.new(address_params)
    if @address.save!
      redirect_to addresses_path
    else
      redirect_to new_address_path
    end
  end

  def destroy
    @address.destroy!
    redirect_to addresses_path
  end

  def update
    @address.update!(address_params)
    redirect_to addresses_path
  end

  def show_all
    @addresses = Address.all
                        .select('latitude as lat, longtitude as lng, address, description')
                        .as_json(only: [:lat, :lng, :address, :description])
  end

  private

  def find_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:name, :latitude, :longtitude, :description, :address)
  end
end

app/views/addresses/_form.html.erb
<%= form_with model: @address, data: { controller: :addresses, 
                                       action: 'google-maps-callback@window->addresses#initMap',
                                       addresses_latitude: @address.latitude,
                                       addresses_longtitude: @address.longtitude } do |form| %>

   <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/2">
      <div class="md:flex md:items-center mb-6">
        <div class="md:w-2/12">
          <%= form.label :name, "Name", class: 'block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4' %>
        </div>
        <div class="md:w-10/12">
          <%= form.text_field :name, class: 'appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-800' %>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-2/12">
          <%= form.label :address, "Address", class: 'block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4'  %>
        </div>
        <div class="md:w-10/12">
          <%= form.search_field :address, size: "60x10", class: 'appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-800', data: { target: 'addresses.field', action: 'keydown->addresses#keydown'} %>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-2/12">
          <%= form.label :latitude, "Latitude", class: 'block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4'  %>
        </div>
        <div class="md:w-10/12">
          <%= form.text_field :latitude, class: 'appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-800', data: { target: 'addresses.latitude'} %>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-2/12">
          <%= form.label :longtitude, "Longtitude", class: 'block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4'  %>
        </div>
        <div class="md:w-10/12">
          <%= form.text_field :longtitude, class: 'appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-800', data: { target: 'addresses.longtitude'} %>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-2/12">
          <%= form.label :description, "Description", class: 'block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4'  %>
        </div>
        <div class="md:w-10/12">
          <%= form.text_area :description, size: "60x10", class: 'appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-800' %>
        </div>
      </div>
      <div class="text-center">
        <%= form.submit class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
      </div>
    </div>
    <div class="md:w-1/2 pl-5">
      <%= content_tag :div, nil, data: { addresses_target: 'map' }, id: 'address_map', class: 'flex' %>
    </div>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1 class="text-center pb-10"> Edit Address</h1>

<%= render 'form'%>

app/views/addresses/index.html.erb
<h1 class="text-center pb-10"> Addresses</h1>

<div class="flex flex-col">
  <div class="h-15">
    <%= link_to 'New address', new_address_path, class: 'float-right bg-blue-500 hover:bg-blue-700 text-white font-bold py-4 px-4 rounded' %>
  </div>
  <div class="my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full table-fixed divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class=" w-1/2 px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Address
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @addresses.each do |address| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <div class="ml-4">
                      <div class="text-sm font-medium text-gray-900">
                        <%= address.name %>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                   <%= address.address%>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Edit', edit_address_path(address), class: 'text-indigo-600 hover:text-indigo-900'%>
                  <%= link_to "Delete", address, data:{ confirm: "Are you sure?", "turbo-method": :delete }, class: 'text-indigo-600 hover:text-indigo-900' %>
                </td>
              </tr>
            <% end %>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/addresses/new.html.erb
<h1 class="text-center pb-10"> New Address</h1>

<%= render 'form'%>

app/views/addresses/show_all.html.erb
<h1 class="text-center pb-10"> Show all Addresses</h1>

<div class="text-center" data-controller="addresses" data-addresses-addresses-value="<%=@addresses.to_json%>" data-action="show-all-adresses@window->addresses#showAllAddresses" >
    <%= content_tag :div, nil, data: { addresses_target: 'map', action: 'google-maps-callback@window->addresses#showAllAddresses' }, id: 'address_map', class: 'flex' %>
</div>