config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :addresses do
    get 'show_all', on: :collection
  end

  namespace :youtube do
    get 'most_popular', to: 'most_popular'
    get 'video_comments', to: 'video_comments'
  end

  namespace :flickr do
    get 'search', to: 'search'
    get 'show_photo', to: 'show_photo'
  end

  resources :movies

  wash_out 'api/soap/movies'
end

app/controllers/flickr_controller.rb
class FlickrController < ApplicationController
  def search
    return unless params[:search].present?

    @photos = flick_api.photos.search(text: params[:search],
                                      extras: 'owner_name, tags, url_m, url_o, views',
                                      page: params_page,
                                      per_page: 10)

    @paginate = Pagination.new(@photos.page, @photos.perpage, @photos.total)
  end

  def show_photo
    @orginal_photo = params[:url_o] ||  params[:url_m]
  end

  private

  def flick_api
    @flick_api ||= Flickr.new(Rails.application.credentials[:flickr][:api_key],
                              Rails.application.credentials[:flickr][:api_secret])
  end

  def params_page
    params[:page] || 1
  end
end

app/views/flickr/_flickr_photo.html.erb
<div class="p-4 w-full md:w-1/3 sm:mb-0 mb-6">
  <%= link_to flickr_show_photo_path(url_o: photo['url_o'], url_m: photo['url_m']), "data-turbo-frame": "show_photo" do %>
    <div class="rounded-lg h-64 overflow-hidden border border-sky-500">
      <img alt="content" class="object-cover object-center h-full w-full" src=<%= photo['url_m'] %>>
    </div>
    <div class="flex flex-row mt-5 justify-between">
      <h2 class="tooltip text-xl font-medium title-font text-gray-900" title="<%=photo['title']%>"><%=photo['title'].truncate(70)%>
      </h2>
      <span class="text-gray-400 mr-3 inline-flex items-center leading-none text-sm py-1">
        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
          <circle cx="12" cy="12" r="3"></circle>
        </svg><%= photo.views %>
      </span>
    </div>
  <% end %>
</div>

app/views/flickr/search.html.erb
<section class="text-gray-600 body-font">
  <div class="flex flex-wrap w-full mb-1">
    <div class="lg:w-1/2 w-full mb-6">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Image search</h1>
      <div class="h-1 w-20 bg-indigo-500 rounded"></div>
    </div>
  </div>
  <div class="mb-10">
    <%= render partial: 'common/search_bar', locals: { search_path: flickr_search_path }%>
  </div>
  <% if @photos.nil? || @photos.size.zero? %>
    <div>
      <p class="w-1/3 text-center mx-auto">No images to show</p>
    </div>
  <% else %>
    <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
      <%= render partial: 'flickr_photo', collection: @photos, as: :photo%>
    </div>
  <% end %>
</section>
<%= turbo_frame_tag :show_photo do %>
<% end %>

<% if @paginate %>
  <div class="text-center my-10">
    <%= will_paginate @paginate %>
  </div>
<% end %>

app/views/flickr/show_photo.html.erb
<%= turbo_frame_tag :show_photo do %>
  <div class="modal fixed w-full h-full top-0 left-0 flex items-center justify-center">
    <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>

    <div class="modal-container h-full w-full md:w-4/5 bg-white mx-auto rounded shadow-lg z-50 overflow-y-auto">
      <%= link_to flickr_search_path do %>
      <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
        <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
          <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
        </svg>
        <span class="text-sm">(Esc)</span>
      </div>
      <% end %>

      <div class="modal-content w-full h-full py-4 text-left px-6">
        <div class="flex justify-between items-center pb-3">
          <p class="text-2xl font-bold">Photo show</p>
          <div class="modal-close cursor-pointer z-50">
            <%= link_to flickr_search_path do %>
              <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
              </svg>
            <% end %>
          </div>
        </div>

        <div>
          <div class="sm:p-5 mx-auto">
            <div class="rounded-lg overflow-hidden border border-sky-500">
              <img alt="content" class="mx-auto object-cover object-center" src=<%= @orginal_photo %>>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>